name: "atopile Publish"

description: "Publish an atopile package."

inputs:
  atopile-version:
    description: "Version of atopile to use for publishing."
    required: true
    default: "latest"
  package-name:
    description: "Name of the package to publish. If empty, the name is expected in the ato.yaml file."
    required: true
    default: ${{ github.repository }}
  package-version:
    description: "Version of the package to publish. If empty, the version is expected in the ato.yaml file."
    required: true
    default: "from-tag"
  registry:
    description: "Registry to publish the package to"
    required: true
    default: "https://packages.atopileapi.com"
  skip-duplicate-version:
    description: "Skip publishing if the version already exists"
    required: false
    default: "true"

# Example output
# outputs:
#   random-number:
#     description: "Random number"
#     value: ${{ steps.random-number-generator.outputs.random-number }}
# TODO: output the URL or the published package
# TODO: hash of the package

runs:
  using: "composite"
  steps:
    - name: Setup uv
      uses: astral-sh/setup-uv@v5
      with:
        version: "latest"
        enable-cache: false

    # TODO: derive atopile version from the ato.yaml

    - name: Publish package
      run: uvx --from git+https://github.com/atopile/atopile@main ato package publish
      # run: uvx --from "atopile@${{ inputs.atopile-version }}" ato package publish
      shell: bash
      env:
        ATO_NAME: ${{ inputs.package-name }} # envvar honored by the config, not specified by the CLI
        ATO_REPOSITORY: ${{ github.repositoryUrl }} # envvar honored by the config, not specified by the CLI
        ATO_PACKAGE_VERSION: ${{ inputs.package-version }}
        ATO_SKIP_DUPLICATE_VERSION: ${{ inputs.skip-duplicate-version }}
        ATO_SERVICES_PACKAGES_URL: ${{ inputs.registry }} # envvar honored by the config, not specified by the CLI
        NONINTERACTIVE: 1
