name: "publish-package"

description: "Publish an atopile package."

inputs:
  atopile-version:
    description: "Version of atopile to use for publishing."
    required: true
    default: "latest"
  package-version:
    description: "Version of the package to publish. If empty, the version is expected in the ato.yaml file."
    required: true
    default: "from-tag"
  registry:
    description: "Registry to publish the package to"
    required: true
    default: "https://packages.atopileapi.com"
  working-directory:
    description: "Working directory to publish the package from"
    required: true
    default: "."
  skip-duplicate-versions:
    description: "Skip publishing if the version already exists"
    required: false
    default: "true"

# TODO: output the URL or the published package
# TODO: hash of the package

runs:
  using: "composite"
  steps:
    - name: Setup uv
      uses: astral-sh/setup-uv@v5
      with:
        version: "latest"
        enable-cache: false

    # TODO: derive atopile version from the ato.yaml

    - name: Publish package
      run: cd ${{ inputs.working-directory }} && uvx --from git+https://github.com/atopile/atopile@feature/ato_cli_deps ato -v package publish
      # run: cd ${{ inputs.working-directory }} && uvx --from "atopile@${{ inputs.atopile-version }}" ato package publish
      shell: bash
      env:
        ATO_CLI_PACKAGE_VERSION: ${{ inputs.package-version }}
        ATO_CLI_PACKAGE_SKIP_DUPLICATE_VERSIONS: ${{ inputs.skip-duplicate-versions }}
        ATO_SERVICES_PACKAGES_URL: ${{ inputs.registry }} # envvar honored by the config, not specified by the CLI
        NONINTERACTIVE: 1
