on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: tailscale/github-action@v3
        with:
            oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
            oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
            tags: tag:ci

      # Dump something out to package and publish
      - run: echo "import Resistor" > test.ato

      - uses: atopile/atopile-package-publish-action@main
        with:
          include-paths: "test.ato"
          registry: "http://100.75.32.89:8000/"
          # atopile-version: ""
